### ISSUE TITLE
Library doesn't display anything not even errors after I2C is found

### ISSUE THREAD

**Issue by Aloy-Lockness11** [stm32duino/VL53L4CX#10]
Hello 
I have encountered an issue while running any of the example sketches where in I am not getting any response from the sensor. It detects the I2C address of the sensor and displays it's address but after that it just doesn't display anything at all in the serial monitor.

All my connections are correct and I have connected the xshut pin and gpio1 pin to where it needs to be

I'm using the Adafruit version of the sensor.
And the master board is the teensy 4.1

If at all I am making a mistake I would like to know where it could be

**Comment by cparata** [comment]
Hello @Aloy-Lockness11 ,
which example are you trying? Maybe you can try to add some checks in the sketch, so you can find where the code hangs. For example, you can try to print the return values of "InitSensor" just to check if the sensor initialization goes well.
Best Regards,
Carlo

**Comment by fpistm** [comment]
No feedback since a while so I close it.
