### ISSUE TITLE
[question] Running multiple VL53L4CX's simultaneously

### ISSUE THREAD

**Issue by elliotnash** [stm32duino/VL53L4CX#11]
I have a project with 2 VL53L4CX's running off a Teensy 4.0 (and I'll want to increase it to 5). I also want my cycle time to be as close to 20ms as possible. With one ToF, this is easily possible, but each call to ClearInterruptAndStartMeasurement takes 6.5ms and each call to GetMultiRangingData takes 8ms, (so around 15ms for each sensor), so with 2 sensors it takes around 30ms a loop and with 5 it would take around 75ms.
Is there a way to start these measurements in parallel? I'm not sure if that time is from busy waiting for a sensor to be ready, or actual processing/data transfer, but it seems it should be possible to range multiple sensors concurrently.

**Comment by cparata** [comment]
Hi @elliotnash ,
you can give a look at [this example](https://github.com/stm32duino/X-NUCLEO-53L4A1/blob/main/examples/X_NUCLEO_53L4A1_HelloWorld/X_NUCLEO_53L4A1_HelloWorld.ino) done for X-NUCLEO-53L4A1 that can mount up to 3 VL53L4CX sensors. This example is done in polling mode. If you have some constraints in terms of timing, you can try to run the same example in interrupt mode. I have never tried with 3 sensors in parallel in interrupt mode, but it should be feasible.
Best Regards,
Carlo

**Comment by fpistm** [comment]
Close as answered
