### ISSUE TITLE
Initialization I2C write too big for some boards.

### ISSUE THREAD

**Issue by caternuson** [stm32duino/VL53L4CX#2]
This I2C write in `VL53L4CX::VL53L4CX_init_and_start_range()`:
https://github.com/stm32duino/VL53L4CX/blob/36487bb4872f102766bfc415089f62c0c626f8bb/src/vl53l4cx_api_core.cpp#L1730-L1737
ends up being 135 bytes in size. That can exceed the buffer size on some boards. For example, on ESP32, the buffer size is 128 bytes:
https://github.com/espressif/arduino-esp32/blob/ba6e82c30d31a2ddc1276a045e0c42a29b38869f/libraries/Wire/src/Wire.h#L38

This results in the last several bytes not being sent and ranging is not actually started.

Problem demonstrated locally using an [Adafruit Feather ESP32 V2](https://www.adafruit.com/product/5400) and ESP32 BSP v.2.0.3 running the `VL53L4CX_Sat_HelloWorld.ino` example from this library. It loops forever waiting for data ready, since ranging was never started.

**Comment by fpistm** [comment]
Hi @caternuson 
I guess we met the same issue on other library and we provide a fix to split transfer based on BUFFER_LENGTH
https://github.com/simondlevy/VL53L5/pull/12/commits/adca519122df22b0f7e45068bb588e3a1be502be

Issue come from this method:
https://github.com/stm32duino/VL53L4CX/blob/8db6bb34221a057c60a9ae59b45b603e2c5e539a/src/vl53l4cx_class.cpp#L122-L144

@cparata are you agree with this ?

**Comment by caternuson** [comment]
Thanks for responding!

FWIW - that fix looks good to me. Similar tricks have been played in the [Adafruit BusIO library](https://github.com/adafruit/Adafruit_BusIO) (an abstraction helper library for I2C and SPI comms) for dealing with this same issue. The I2C transfers are broken up into "chunks" as needed based on a board's buffer size.

Also totally agree the fix should be in `VL53L4CX::VL53L4CX_I2CWrite`. The code lines I link in original post are just an example of a call with a long (135 bytes) output length. There may be other calls elsewhere with similarly long output lengths.

**Comment by cparata** [comment]
Hi @caternuson ,
I updated the main repository with the fix on the I2C buffer size. Please, let me know if it works on your hardware. If so, I will release v1.0.1 of the library that includes this fix.
Best Regards,
Carlo

**Comment by caternuson** [comment]
Awesome. Thanks. Looks good.

Retesting same `VL53L4CX_Sat_HelloWorld.ino` example on same ESP32 setup above, it now works:
![Screenshot from 2022-05-19 07-32-34](https://user-images.githubusercontent.com/8755041/169322149-ec99645f-a0b7-41cf-b392-eaf20b189ee9.png)

**Comment by cparata** [comment]
Hello @caternuson ,
now it is clear that the I2C transactions are fine, so we can close this issue, but the values that you are reading are quite strange (like negative values for the proximity). Did you remove the tape from the sensor?
Best Regards,
Carlo

**Comment by caternuson** [comment]
Oh..good eye. The tape is removed. Let me look at this a little more. I've got the setup hooked up to a scope, so will take a look at the actual I2C traffic.

**Comment by cparata** [comment]
This is the output on my side if the sensor is covered by my hand: 

![Log_OK](https://user-images.githubusercontent.com/16096427/169328621-ff15744b-b1e0-4cb7-9166-bd759bc1bac3.PNG)

**Comment by caternuson** [comment]
This appears to be an ESP32 specific quirk with how it handles
```cpp
dev_i2c->endTransmission(false);
```
Here is the total I2C output for the 135 byte init:
![image](https://user-images.githubusercontent.com/8755041/169347843-04c39d5b-ac23-4396-b243-1735b21c727a.png)
Only the last 7 bytes are written. That explains why it was "working" in terms of returning values, since the start ranging is in the last byte. But since it never sent all the other initialization bytes, it's in some weird state and the returned values are wrong.

It appears you are not taking advantage of the VL53L4CX's auto increment indexing feature, since you send the starting register address for each chunk each time:
https://github.com/stm32duino/VL53L4CX/blob/10eb10af314af21c75939d60db251a9d6064be18/src/vl53l4cx_class.cpp#L142-L143

So suppressing the STOP may not be needed?

I modified the code to call `endTransmission()` each time:
```cpp
  while (i < NumByteToWrite) {
    // If still more than DEFAULT_I2C_BUFFER_LEN bytes to go, DEFAULT_I2C_BUFFER_LEN,
    // else the remaining number of bytes
    size_t current_write_size = (NumByteToWrite - i > DEFAULT_I2C_BUFFER_LEN ? DEFAULT_I2C_BUFFER_LEN : NumByteToWrite - i);

    dev_i2c->beginTransmission((uint8_t)((DeviceAddr >> 1) & 0x7F));

    // Target register address for transfer
    buffer[0] = (uint8_t)((RegisterAddr + i) >> 8);
    buffer[1] = (uint8_t)((RegisterAddr + i) & 0xFF);
    dev_i2c->write(buffer, 2);
    if (dev_i2c->write(pBuffer + i, current_write_size) == 0) {
      return 1;
    } else {
      i += current_write_size;
      dev_i2c->endTransmission();
    }
  }

  return;
  ```
and now it writes out everything:
![image](https://user-images.githubusercontent.com/8755041/169349307-98c14c51-fe38-49ca-91df-497dff5f5b4f.png)

And with a finger on the sensor, the values look more reasonable and inline with your readings:
![Screenshot from 2022-05-19 09-24-26](https://user-images.githubusercontent.com/8755041/169350419-bcf432af-33b8-4d2b-9bf1-8fccba086669.png)

**Comment by cparata** [comment]
Hello @caternuson ,
thanks to have shared your outcomes. Basically, we need to send the address of the register in each chunk because it is like the big transaction is divided in several small transactions. So, we are obliged to send the new register address in each chunk. It seems like that ESP32 Arduino Core does not manage correctly the I2C transaction when the STOP bit is not sent. 
In order to be compatible also with ESP32 platforms, I guess that it is sufficient to send the STOP for each chunk. So, I modified the library accordingly. Can you check if it works also with ESP32 platform so we can close this ticket and release a new version of the library with the fix?
Best Regards,
Carlo

**Comment by caternuson** [comment]
Thanks. Confirming latest commit works as expected with ESP32:

Example runs and with finger over sensor reports expected results:
![Screenshot from 2022-05-23 07-05-30](https://user-images.githubusercontent.com/8755041/169837729-ba628ab0-ada0-4fbd-8150-e24ce4b92642.png)

**Comment by cparata** [comment]
Great! I close the issue and release a new version of the library.
Best Regards,
Carlo
