### ISSUE TITLE
Getting error in range measurement more than 2m in vl53l4cx with esp32s3

### ISSUE THREAD

**Issue by Pratiksha0102** [stm32duino/VL53L4CX#5]
Hello!!

Greetings!!

I am using vl53l4cx with esp32s3 and it works fine in range up to 2m. But I am getting error with range more than 2m although its max range is 6m. It gives coercion value 8191 and status code 12, 255 in rage of more than 2m. I tried to get a value in the range of more than 2 meters by changing the tuning parameters as suggested in the user manual But it didn't work. I have changed timing budget to 40ms and set long distance mode but still I am not getting valid range.

This is what I get at ranges up to 2m.
![Screenshot from 2022-06-18 15-43-42](https://user-images.githubusercontent.com/99065005/174433764-28f4e227-2961-4067-8b1d-a584c9c79a10.png)

And this is what I get in a range over 2m.
![Screenshot from 2022-06-18 15-43-55](https://user-images.githubusercontent.com/99065005/174433802-495fd1d7-adf4-4f7d-a736-f905d5ed01ed.png)

I have put the sensor on the wall and also tried in light mode and dark mode but there is some problem with more than 2m range.

Can anyone guide me what to do with this kind of error?
How to make this sensor work in maximum range.

**Comment by cparata** [comment]
Hi @Pratiksha0102 ,
what is your hardware setup? What is the color of your target? If it is very dark, it is normal that the maximum range is about 2000 mm.

![Capture](https://user-images.githubusercontent.com/16096427/174547481-846258ef-c0dd-471c-888f-5ef9054430ae.PNG)

Best Regards,
Carlo

**Comment by Pratiksha0102** [comment]
Hello @cparata !
Thanks for your response,
My target is cardboard box with the height of 30cm and the floor is white. The height of the ceiling is 3m.
This is my set-up. Sensor is upside on the ceiling . I am facing issue targeting the box. sometimes it detects valid range but most of the time gives random values like 456, 675, 354, -433, 8191 etc.. 

![IMG_20220620_141647](https://user-images.githubusercontent.com/99065005/174563503-28822a96-6d42-42e0-b384-c35cc6989c1d.jpg)
![IMG_20220620_141237](https://user-images.githubusercontent.com/99065005/174564076-53aec5ec-7b08-4bc2-bba6-4ab62cc0c690.jpg)
![IMG_20220620_141229](https://user-images.githubusercontent.com/99065005/174564116-06b99f74-7137-4599-9213-846627dd7637.jpg)

Thanks & regards.

**Comment by cparata** [comment]
Hello @Pratiksha0102 ,
first of all you should filter the outputs of the sensor. If the range status is 255 or 12, the measurement is not reliable and you should skip it. Another point, if you invert the position of the sensor, for example putting it on the floor, is it able to measure correctly the height of the ceiling?
Best Regards,
Carlo

**Comment by Pratiksha0102** [comment]
Hello @cparata ,
Thanks for your quick response,
I have already ignored that values in main application however i printed that on serial for my reference so that i can observer how many times this error occurs.And ignoring this error for few mins is not suitable for my application it will give some delay and i can not afford it. Yes i have tried to invert the condition by putting the sensor on the floor and it gives valid range of the ceiling. Is it any orientation issue or any calibration issue?

Thanks & regards,
Pratiksha.

**Comment by cparata** [comment]
Hi @Pratiksha0102 ,
If the inverted condition works as expected, it means that it could be also a problem of the orientation of the sensor (it could be not perfectly aligned to the ceiling or the ceiling could be not perfectly parallel to the floor). It could be also an issue of the target that is too small with respect to the field of view of the sensor when it is attached to the ceiling. Could you try to put 4 card boxes (with the same height) close each other a see if the detection improves?
Best Regards,
Carlo

**Comment by Pratiksha0102** [comment]
Hello @cparata ,
Greetings!!
Okay I'll try that way and will update you soon.Thanks for your support.

**Comment by fpistm** [comment]
No feedback since a while. Close it.
