### ISSUE TITLE
Question: Is VL53L4CX the same device as the VL53L4CD?

### ISSUE THREAD

**Issue by ChuckVanzant** [stm32duino/VL53L4CX#7]
I ask this question because the driver for either device appears to work for either device.

The following is output during initialization of objects for each device driver for the same physical device:

VL53L4CD Driver Sensor Id: 0xEBAA

VL53L4CX Driver Device Type: AA  Product Revision: 1.1  Product version: 8 1 2 2578

Are the physical devices actually different or 
Are they the same but the VL53L4CX driver provides more, expanded functionality?

**Comment by AnneBigot** [comment]
The official rule is you should use the driver delivered with the sensor.
This is not recommended by ST to use a different driver but if you test it, it might work for you.
