### ISSUE TITLE
library hangs when getting ranging data

### ISSUE THREAD

**Issue by crides** [stm32duino/VL53L4CX#9]
Hi, I'm using 3 VL53L4CX's on my board. They were working but today when I perform the `VL53L4CX_GetMultiRangingData` API call the library hangs. All init procedures show it's fine. Could this be a bug or is there something wrong with the device (and how could I find out?)? Thanks!

**Comment by cparata** [comment]
Hello @crides ,
what is your hardware setup? Can you share your code? If the sensors worked for a while and then some sensors stopped to work, it could be an hardware issue.
Best Regards,
Carlo

**Comment by fpistm** [comment]
No update since a while. Close it.
